### ISSUE TITLE
Ability to get document via `indexAPI.get`

### ISSUE THREAD

**Issue by scruel** [manticoresoftware/manticoresearch-python#12]
Currently, I can only filter with `searchAPI` to get the document via its ID or field, I wonder if you could let `indexAPI` provide a more easy way to do so.

**Comment by sanikolaev** [comment]
Do you mean smth like this in Elastic https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html ?

**Comment by scruel** [comment]
Yeap, it is, but for field filtering, I'd also want to have a similar API.

**Comment by sanikolaev** [comment]
> for field filtering, I'd also want to have a similar API.

What do you mean? There's already `searchAPI` for field filtering. Isn't it enough?

**Comment by scruel** [comment]
Want to make
```python
search_request = SearchRequest(
    index="index_example",
    query={"bool": {"must": [{"equals": {"field": value}}]}}
)
res = searchApi.search(search_request).hits.hits[0]["_source"]
```

be simplified to:
```python
get_document_request = GetDocumentRequest(
    index="index_example",
    fileds={"field": value},
)
res = api_instance.get(get_document_request)
```

Or even:
```python
res = api_instance.get(
    index="index_example",
    fileds={"field": value},
)
```

**Comment by sanikolaev** [comment]
Have you tried this https://github.com/manticoresoftware/manticoresearch-python/blob/27a6d66c2c957d55ab3dea85d3580982112ff58f/manticoresearch/model/equals_filter.py#L18 ?

**Comment by scruel** [comment]
Nope, and thanks for bringing it to me, but still, it will require me to write:
```python
search_request = SearchRequest(
    index="index_example",
    query={'equals': {"field" : value}}
)

res = searchApi.search(search_request).hits.hits
if res:
    res = res[0]["_source"]
```
Or:
```python
search_request = manticoresearch.model.SearchRequest(index='index_example')
search_request.attr_filter = manticoresearch.model.EqualsFilter('field', value)
res = searchApi.search(search_request).hits.hits[0]["_source"]
if res:
    res = res[0]["_source"]
```

But I hope to have an API like:
```python
# or indexApi?
res = searchApi.get(
    index="index_example",
    fileds={"field": value},
)
if res.found:
    res = res["_source"]
```

It is clear and cleaner, and even `SearchRequest` is required, the code of creating those objects can be hidden within the `get` method.

**Comment by sanikolaev** [comment]
Thanks. We'll discuss it within the team.

**Comment by scruel** [comment]
And you can also consider to have the `httpx` lib style, so instead of:
```python
res.raise_for_status()
res = res["_source"]
```

instead of
```python
if res.found:
    res = res["_source"]
```
