### ISSUE TITLE
Question about `query` and `filter`s field.

### ISSUE THREAD

**Issue by scruel** [manticoresoftware/manticoresearch-python#16]
What is the purpose of `fulltext_filter` and `attr_filter`? It seems that your [documentation](https://manual.manticoresearch.com) didn't contain such related info about them:
![image](https://github.com/manticoresoftware/manticoresearch-python/assets/16933298/d4569f83-1054-494e-8aa7-a82a0f3ce19e)

Furthermore, I would like to know what is the difference between the following code snippets:
```
search_req = SearchRequest(
  index='test',
  query={'match': {"title": "word"}},
  fulltext_filter={'match': {"title": "table"}},
)
search_req = SearchRequest(
  index='test',
  query={'bool': {'must': [
         'match': {"title": "word"},
         'match': {"title": "table"}
        ]}}
)
```

**Comment by Nick-S-2018** [comment]
`attr_filter` lets you add search conditions based on attribure values.
`fulltext_filter` adds conditions for full-text search. It overwrites conditions set with `query` if such exist. So, in your first example the search will be performed only by the "title=word" condition.

In fact, this functionality will be disabled in the near future after we update our OpenAPI  schema and all auto-generated clients including the Python one.

**Comment by scruel** [comment]
Thanks for your answer, which way will be disabled? `fulltext_filter` or `attr_filter`?

**Comment by Nick-S-2018** [comment]
Both of them.
